### ISSUE TITLE
Original From: header isn't being removed

### ISSUE THREAD

**Issue by ciencia** [zoni/postforward#8]
On my installation this doesn't seem to work as expected. The Reply-To: header is rewritten correctly, but not the From: header.

Debugging the issue, I see your code removes the first line that has a "From " (without colon), but then it also receives the original "From: " header that this program leaves untouched. Apparently, postfix doesn't rewrite the "From: " header that's passed to the sendmail program, and the message is forwarded with the original "From: " header, causing it to fail de DKIM and DMARC validations.

I did some modifications to the script, to remove the "From: " header, and now it works. I've done it on a local fork here: https://github.com/ciencia/postforward/commit/06c5a463723e30538eea259ff9a0e3cfb618353d

This bug defeats the whole purpose of this program, so I think there may be something in my configuration causing this behavior. I'm opening this just to inform you about my situation, in case there's some config change needed for making it work as described, or to review my change in case you want to apply a similar change in your program. Feel free to close it once read if there's nothing to do.

**Comment by julian-klode** [comment]
Not changing From: is absolutely correct. Only the enveloper sender matters for SRS.

**Comment by julian-klode** [comment]
That is, "From " is the envelope sender. This defines where bounces go to. It might be entirely different from "From:" which is the sender of the email.

Bounces are emails sent back from a server to the envelope sender to inform them that an email could not be delivered.

A common example are mailing lists. They set "From bounces@lists.example.com", but still keep your "From: me@mydomain.example".

Now what SRS does is change the enveloper sender so that bounces go to the forwarding server instead of the original server, and the forwarder than "backwards" (;)) that bounce to the original sender (or well, a previous forwarder).

**Comment by ciencia** [comment]
Ok, after further investigation and tests, I had to add `SenderHeaders           Sender,From` to opendkim.conf (default for Debian seems to be `From`) and it seems to not generate invalid signatures anymore, but it doesn't sign the forwarded messages...

Well, that's not what I expected, I'd expect it to change the From: header as well, and opendkim to sign all forwarded messages, but on the other hand it makes sense to prevent someone abusing the forward to compromise the reputation of the server... Fair enough
